name: arian-venv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cuda-cudart=12.4.127=0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-version=12.8=h30beaf8_3
  - expat=2.7.3=h7354ed3_4
  - faiss-gpu=1.9.0=py3.12_ha2e4562_0_cuda12.1.1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.8.4.1=hbdd6827_1
  - libexpat=2.7.3=h7354ed3_4
  - libfaiss=1.9.0=h4818125_0_cuda12.1.1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.5=h7934f7d_0
  - numpy=1.26.4=py312hc213724_1
  - numpy-base=1.26.4=py312hf387b04_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py312h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=3_cp312
  - readline=8.3=hc2a1206_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=he0a8d7e_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.10.1
      - ag-ui-protocol==0.1.10
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.12.1
      - apache-tvm-ffi==0.1.8.post2
      - argcomplete==3.6.3
      - ascii-colors==0.11.7
      - astor==0.8.1
      - attrs==25.4.0
      - authlib==1.6.6
      - bcrypt==5.0.0
      - beartype==0.22.9
      - beautifulsoup4==4.13.5
      - blake3==1.0.8
      - blinker==1.9.0
      - blis==1.3.3
      - boto3==1.42.27
      - botocore==1.42.27
      - cachetools==6.2.4
      - catalogue==2.0.10
      - cbor2==5.8.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.2
      - cohere==5.20.1
      - colorama==0.4.6
      - colorclass==2.2.2
      - compressed-rtf==1.0.7
      - compressed-tensors==0.12.2
      - confection==0.1.5
      - configparser==7.2.0
      - cryptography==46.0.3
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - cyclopts==4.4.5
      - cymem==2.0.13
      - dataclasses-json==0.6.7
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.22.4
      - easygui==0.98.3
      - ebcdic==1.1.1
      - ecdsa==0.19.1
      - einops==0.8.1
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - extract-msg==0.55.0
      - fakeredis==2.33.0
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.10.1
      - fastar==0.8.0
      - fastavro==1.12.1
      - fastmcp==2.14.3
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flashinfer-python==0.5.3
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - genai-prices==0.0.51
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - google-genai==1.57.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.0
      - griffe==1.15.0
      - groq==1.0.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - ijson==3.4.0.post0
      - importlib-metadata==8.7.1
      - interegular==0.3.3
      - invoke==2.2.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.1.0
      - jaraco-functools==4.4.0
      - jeepney==0.9.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - json-repair==0.44.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - keyring==25.7.0
      - langchain==1.2.3
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.7
      - langchain-huggingface==1.2.0
      - langchain-neo4j==0.7.0
      - langchain-ollama==1.0.1
      - langchain-openai==1.1.7
      - langchain-text-splitters==1.1.0
      - langcodes==3.5.1
      - langdetect==1.0.9
      - langgraph==1.0.6
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.6
      - langgraph-sdk==0.3.3
      - langsmith==0.6.2
      - lark==1.2.2
      - lightrag-hku==1.4.9.11
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - logfire==4.18.0
      - logfire-api==4.18.0
      - loguru==0.7.3
      - lupa==2.6
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.2
      - mcp==1.25.0
      - mdurl==0.1.2
      - mistral-common==1.8.8
      - mistralai==1.9.11
      - model-hosting-container-standards==0.1.13
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - msoffcrypto-tool==6.0.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - murmurhash==1.0.15
      - mypy-extensions==1.1.0
      - nano-vectordb==0.0.4.3
      - narwhals==2.15.0
      - neo4j==6.1.0
      - neo4j-graphrag==1.12.0
      - networkx==3.6.1
      - nexus-rpc==1.2.0
      - ninja==1.13.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.17.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.5
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - olefile==0.47
      - oletools==0.60.2
      - ollama==0.6.1
      - openai==2.15.0
      - openai-harmony==0.0.8
      - openapi-pydantic==0.5.1
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-http==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-instrumentation==0.60b1
      - opentelemetry-instrumentation-httpx==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opentelemetry-util-http==0.60b1
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - outlines-core==0.2.11
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pathable==0.4.4
      - pathvalidate==3.3.1
      - pcodedmp==1.2.6
      - pillow==12.0.0
      - pipmaster==1.1.0
      - platformdirs==4.5.1
      - preshed==3.0.12
      - prometheus-client==0.24.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - psutil==7.2.1
      - py-cpuinfo==9.0.0
      - py-key-value-aio==0.3.0
      - py-key-value-shared==0.3.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-ai==1.42.0
      - pydantic-ai-slim==1.42.0
      - pydantic-core==2.41.5
      - pydantic-evals==1.42.0
      - pydantic-extra-types==2.11.0
      - pydantic-graph==1.42.0
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pydocket==0.16.6
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.3.1
      - pypdf==6.6.0
      - pyperclip==1.11.0
      - pypinyin==0.55.0
      - pytesseract==0.3.13
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-jose==3.5.0
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.53.0
      - red-black-tree-mod==1.22
      - redis==7.1.0
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rich-rst==1.3.2
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.9.1
      - rtfde==0.1.2.2
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scipy==1.17.0
      - secretstorage==3.5.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.49.0
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - soxr==1.0.0
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.45
      - srsly==2.5.2
      - sse-starlette==3.1.2
      - starlette==0.50.0
      - streamlit==1.51.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - temporalio==1.20.0
      - tenacity==9.1.2
      - thinc==8.3.10
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.9.0+cu128
      - torchaudio==2.9.0+cu128
      - torchvision==0.24.0+cu128
      - tornado==6.5.4
      - tqdm==4.67.1
      - transformers==4.57.5
      - triton==3.5.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - types-protobuf==6.32.1.20251210
      - types-pyyaml==6.0.12.20250915
      - types-requests==2.32.4.20260107
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - tzlocal==5.3.1
      - urllib3==2.6.3
      - uuid-utils==0.13.0
      - uv==0.9.25
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - vllm==0.13.0
      - wasabi==1.1.3
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - weasel==0.4.3
      - websockets==15.0.1
      - wrapt==1.17.3
      - xformers==0.0.32.post1
      - xgrammar==0.1.27
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/chryssida/miniconda3/envs/arian-venv
